# Site settings
title: Guiceolin.dev
email: guiceolin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gui Ceolin`s development blog. Here i write about Ruby, Rails,
  and all web development ecosystem.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://guiceolin.github.io" # the base hostname & protocol for your site
twitter_username: guiceolin
github_username: guiceolin

# Build settings
markdown: kramdown
exclude: ['vendor/cache']
